### PR TITLE
Optimization, reformatting, spelling fixes, clean up test.py a bit, a…

### PR DESCRIPTION
**Pull request by QuartzWarrior**
…nd remove unnecessary library.

### CODE REVIEW

**Comment by QuartzWarrior** [comment]
@mishalhossin, did some of my new code break the bot?

**Comment by mishalhossin** [comment]
> @mishalhossin, did some of my new code break the bot?
My stupid brain didnt understand the new syntax

**Comment by mishalhossin** [comment]
Also my skill issue

**Comment by QuartzWarrior** [comment]
💀 You can tell me exactly which parts and I can keep them how they are and update the rest.

**Pull request merged**
